# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(blank=True, max_length=100)),
                ('p2', models.CharField(blank=True, max_length=100)),
                ('p3', models.CharField(blank=True, max_length=100)),
                ('p4', models.CharField(blank=True, max_length=100)),
                ('p5', models.CharField(blank=True, max_length=100)),
                ('p6', models.CharField(blank=True, max_length=100)),
                ('p7', models.CharField(blank=True, max_length=100)),
                ('p8', models.CharField(blank=True, max_length=100)),
                ('p9', models.CharField(blank=True, max_length=100)),
                ('p10', models.CharField(blank=True, max_length=100)),
                ('p11', models.CharField(blank=True, max_length=100)),
                ('p12', models.CharField(blank=True, max_length=100)),
                ('p13', models.CharField(blank=True, max_length=100)),
                ('p14', models.CharField(blank=True, max_length=100)),
                ('p15', models.CharField(blank=True, max_length=100)),
                ('p16', models.CharField(blank=True, max_length=100)),
                ('p17', models.CharField(blank=True, max_length=100)),
                ('p18', models.CharField(blank=True, max_length=100)),
                ('p19', models.CharField(blank=True, max_length=100)),
                ('p20', models.CharField(blank=True, max_length=100)),
                ('p21', models.CharField(blank=True, max_length=100)),
                ('p22', models.CharField(blank=True, max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Custom')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Pack2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p23', models.CharField(blank=True, max_length=100)),
                ('r23', models.CharField(blank=True, max_length=100)),
                ('p24', models.CharField(blank=True, max_length=100)),
                ('r24', models.CharField(blank=True, max_length=100)),
                ('p25', models.CharField(blank=True, max_length=100)),
                ('r25', models.CharField(blank=True, max_length=100)),
                ('p26', models.CharField(blank=True, max_length=100)),
                ('r26', models.CharField(blank=True, max_length=100)),
                ('p27', models.CharField(blank=True, max_length=100)),
                ('r27', models.CharField(blank=True, max_length=100)),
                ('p28', models.CharField(blank=True, max_length=100)),
                ('r28', models.CharField(blank=True, max_length=100)),
                ('p29', models.CharField(blank=True, max_length=100)),
                ('r29', models.CharField(blank=True, max_length=100)),
                ('p30', models.CharField(blank=True, max_length=100)),
                ('r30', models.CharField(blank=True, max_length=100)),
                ('p31', models.CharField(blank=True, max_length=100)),
                ('r31', models.CharField(blank=True, max_length=100)),
                ('p32', models.CharField(blank=True, max_length=100)),
                ('r32', models.CharField(blank=True, max_length=100)),
                ('p33', models.CharField(blank=True, max_length=100)),
                ('r33', models.CharField(blank=True, max_length=100)),
                ('p34', models.CharField(blank=True, max_length=100)),
                ('r34', models.CharField(blank=True, max_length=100)),
                ('p35', models.CharField(blank=True, max_length=100)),
                ('r35', models.CharField(blank=True, max_length=100)),
                ('p36', models.CharField(blank=True, max_length=100)),
                ('r36', models.CharField(blank=True, max_length=100)),
                ('p37', models.CharField(blank=True, max_length=100)),
                ('r37', models.CharField(blank=True, max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Custom')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
