# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_pack1_pack2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack2',
            name='p37',
        ),
        migrations.RemoveField(
            model_name='pack2',
            name='r37',
        ),
    ]
